### ISSUE TITLE
Mecánica de dos tiempos

### ISSUE THREAD

**Issue by nicolascian** [MarianoCinalli/tallerDeProgramacionI#4]
Se juegan dos tiempos, en cada uno inicial con la pelota el otro equipo.
Implementar el cambio de cancha.

**Comment by nicolascian** [comment]
Nexus: ¿Qué es lo que hay que mostrar cuando termina el partido?
-- 
Al finalizar el partido hay que mostrar los goles del equipo y los goles de cada usuario.

**Comment by MarianoCinalli** [comment]
Listo.
