### ISSUE TITLE
Movimiento jugadores no activos

### ISSUE THREAD

**Issue by nicolascian** [MarianoCinalli/tallerDeProgramacionI#7]
Areas en las que se mueven, distancia de quitar la pelota.

**Comment by nicolascian** [comment]
Developers: ¿Áreas de marca?
-- 
Cada jugador tiene un área predefinida en la que se mueve cuándo no está activo. El área puede ser divisiones de la cancha o un área a parir de la posición inicial del jugador.
Cuándo se defiende va a buscar la pelota, pero sin salir de su area. Cuando ataca, avanza acompañando la pelota, también sin salir del área.

**Comment by nicolascian** [comment]
Developers: ¿Manejo del arquero?
--
Lo propuesto es seguir a la pelota en el eje "y" con algún delay adicional, tratando de mantenerlo en el área. El arquero se tira cuando la pelota está a cierta distancia, dando un margen adicional para agarrarla.
Si el arquero toma la pelota que haga un pase (cualquiera de los 3, por ejemplo el dirigido) para poder seguir el juego.

**Comment by MarianoCinalli** [comment]
Los jugadores se mueven en sus areas. El arquero se mueve en Y.  Falta que ataje, cierro este issue y creo otro para el arquero.
