### ISSUE TITLE
Pase elevado con intensidad

### ISSUE THREAD

**Issue by nicolascian** [MarianoCinalli/tallerDeProgramacionI#8]

**Comment by nicolascian** [comment]
Developers: ¿Qué tipo de pases hay?
-- 
Tres tipos de pase:

- Toque corto que "busque" compañeros, directo

- Pase por el piso con intensidad proporcional al tiempo que apretó la tecla. Dirección recta, indirecto, no va directo al compañero

- Pase aéreo, también teniendo en cuenta la intensidad

Los últimos dos sirven para patear al arco.

**Comment by nicolascian** [comment]
La mayoría lo esta resolviendo con 3 teclas, yo pregunte y me dijo que podemos hacerlo con 2 teclas.

**Comment by MarianoCinalli** [comment]
Esto creo que tambien ya esta
